version: '3'

services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanopi-backend
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
    ports:
      - "5001:80"
    tty: true
    volumes:
      - ./backend:/app
    networks:
      - kanopi-network
      
  frontend:
    build: ./frontend
    container_name: kanopi-frontend
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - kanopi-network

networks:
  kanopi-network:
    driver: bridge